# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: dfb0404
_src_path: https://github.com/qiime2/q2-setup-template.git
module_name: fondue
plugin_name: q2_fondue
plugin_scripts: null
project_author_email: ziemski.michal@gmail.com
project_author_name: Michal Ziemski
project_description: null
project_name: q2-fondue
project_urls_homepage: https://github.com/bokulich-lab/q2-fondue
project_urls_repository: https://github.com/bokulich-lab/q2-fondue
