// ESearch request
GET https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi
    ?email=mziemski%40ethz.ch
    &db=biosample
    &term=txid410656%5BOrganism%5D+AND+biosample+sra%5BFilter%5D+AND+%22public%22%5BFilter%5D+AND+%28mouse+OR+rat+OR+pig+OR+dog+OR+human%29
    &retmode=json
    &retmax={{ retmax }}
    &retstart=0
#    &usehistory=y

> {%
 var webenv = response.body.esearchresult.webenv
 var qkey = response.body.esearchresult.querykey
 var ids = response.body.esearchresult.idlist.join(",")
 client.global.set("esearch_retmax", response.body.esearchresult.idlist.length)
 client.log(`${webenv}, ${qkey}, ${ids}`)
 client.global.set("esearch_webenv", webenv)
 client.global.set("esearch_qkey", qkey)
 client.global.set("esearch_ids", ids)
 %}
<> 2022-07-07T080418.200.json

###
// ELink request
GET https://eutils.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi
    ?email=mziemski%40ethz.ch
    &dbfrom=biosample
    &db=sra
    &cmd=neighbor_history
    &retmode=json
    &id={{ esearch_ids }}
#    &WebEnv={{ esearch_webenv }}
#    &query_key={{ esearch_qkey }}

> {%
 var webenv = response.body.linksets[0].webenv
 var qkey = response.body.linksets[0].linksetdbhistories[0].querykey
 var ids_len = response.body.linksets[0].ids.length
 var first_id = response.body.linksets[0].ids[0]
 client.log(`${webenv}, ${qkey}, ${ids_len} IDs, first ID was: ${first_id}`)
 client.global.set("elink_webenv", webenv)
 client.global.set("elink_qkey", qkey)
 %}

###
// EFetch request
GET https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi
    ?email=mziemski%40ethz.ch
    &db=sra
    &retmode=xml
    &rettype=docsum
    &retstart=0
    &retmax=10000
    &WebEnv={{ elink_webenv }}
    &query_key={{ elink_qkey }}

> {%
 var id_count = (response.body.match(/<DocSum>/g) || []).length;
 // client.log(`There were ${id_count} IDs in the response.`)
 client.log(parseInt(client.global.get("esearch_retmax")))
 client.test("Request executed successfully", function() {
   client.assert(id_count <= parseInt(client.global.get("esearch_retmax")), `Only ${id_count} IDs were found`);
 });
 %}
