{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-fondue
  version: {{ version }}

source:
  path: ../..

build:
  script: | 
    make VERBOSE=1
    make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - entrezpy >=2.1.2
    - xmltodict
    - python {{ python }}
    - python-dotenv
    - pyzotero
    - q2-types {{ qiime2_epoch }}.*
    - qiime2 {{ qiime2_epoch }}.*
    - tqdm >=4.62.3

test:
  imports:
    - q2_fondue
    - qiime2.plugins.fondue
  requires:
    - parameterized
    - coverage
    - pytest-cov
  commands:
    - pytest --cov q2_fondue --cov-report xml:coverage.xml --pyargs q2_fondue

about:
  home: https://github.com/bokulich-lab/q2-fondue
  license: BSD-3-Clause
  license_family: BSD
