{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-fondue
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - xmltodict
    - pyzotero
    - python-dotenv
    - tqdm >=4.62.3
    - entrezpy >=2.1.2
    - q2-types {{ release }}.*
    - qiime2 {{ release }}.*

test:
  imports:
    - q2_fondue
    - qiime2.plugins.fondue

about:
  home: https://github.com/bokulich-lab/q2-fondue
  license: BSD-3-Clause
  license_family: BSD
