name: Test env files
on:
  pull_request:
    branches: ["main"]
    paths:
      - 'environment-files/**'
  push:
    branches: ["main"]
    paths:
      - 'environment-files/**'
  workflow_dispatch:

jobs:
  ci:
    uses: bokulich-lab/utilities/.github/workflows/test-env-files.yaml@main
    with:
      environment_dir: environment-files
      test_all: true   # every file in the dir whenever this runs
